[project]
name = "pyrengine"
version = "1.0.0"
description = "Personal blog engine written in Python using Flask and SqlAlchemy"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Sergey Stolyarov", email="sergei@regolit.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "Flask==2.3.3",
    "Flask-SQLAlchemy==3.0.5",
    "Flask-Migrate==4.0.4",
    "Flask-Babel==3.1.0",
    "Flask-Login==0.6.2",
    "pytz",
    "markdown==3.4.4",
    "Pygments==2.16.1",
    "humanize==4.8.0",
    "lxml==4.9.3",
    "psycopg2==2.9.7",
# pinned auto deps
    "Jinja2==3.1.2",
    "click==8.1.7",
    "blinker==1.6.2",
    "Babel==2.12.1",
    "alembic==1.11.3",
    "sqlalchemy==2.0.20",
    "Mako==1.2.4",
    "typing-extensions==4.7.1",
    "MarkupSafe==2.1.3",
    "greenlet==2.0.2"
]

[build-system]
requires = [ "flit_core<4" ]
build-backend = "flit_core.buildapi"

[project.urls]
"Homepage" = "https://github.com/sigsergv/pyrengine"
