[project]
dynamic = ["version"]
name = "pyrengine"
#version = "1.0.0"
description = "Personal blog engine written in Python using Flask and SqlAlchemy"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Sergey Stolyarov", email="sergei@regolit.com" },
]
classifiers = [
    "Framework :: Flask",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "Flask==2.3.3",
    "Flask-SQLAlchemy==3.0.5",
    "Flask-Migrate==4.0.4",
    "Flask-Babel==3.1.0",
    "Flask-Login==0.6.2",
    "pytz",
    "markdown==3.4.4",
    "Pygments==2.16.1",
    "humanize==4.8.0",
    "lxml==4.9.3",
    "psycopg2==2.9.7",
# pinned auto deps
    "Jinja2==3.1.2",
    "click==8.1.7",
    "blinker==1.6.2",
    "Babel==2.12.1",
    "alembic==1.11.3",
    "sqlalchemy==2.0.20",
    "Mako==1.2.4",
    "typing-extensions==4.7.1",
    "MarkupSafe==2.1.3",
    "greenlet==2.0.2"
]

#[tool.setuptools]
#package-dir = {"" = "pyrengine"}

#[tool.setuptools.packages]
#find = {}  # Scanning implicit namespaces is active by default

[tool.setuptools.dynamic]
version = {attr = "pyrengine.__version__"}

[tool.setuptools.packages.find]
exclude = ["__pycache__"]

[tool.setuptools.package-data]
# add templates recursiveley
"pyrengine.templates" = ["**/*.jinja2"]
# add everything in "pyrengine/static" directory
"pyrengine.static" = ["**/*"]
"pyrengine.examples" = ["**/*"]
"pyrengine.translations" = ["**/*"]
"pyrengine.models.migrations" = ["**/*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.pyc"]


[build-system]
requires = ["setuptools >= 62.3.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/sigsergv/pyrengine"
