"""Initial migration.

Revision ID: 525c1f82801f
Revises: 
Create Date: 2023-09-02 10:01:11.993676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525c1f82801f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pbconfig',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbstoragefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('dltype', sa.String(length=10), nullable=True),
    sa.Column('etag', sa.String(length=50), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pbuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbverifiedemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verify_date', sa.Integer(), nullable=True),
    sa.Column('verification_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pbarticle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shortcut_date', sa.Unicode(length=50), nullable=True),
    sa.Column('shortcut', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.Column('rendered_preview', sa.UnicodeText(), nullable=True),
    sa.Column('rendered_body', sa.UnicodeText(), nullable=True),
    sa.Column('published', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('comments_total', sa.Integer(), nullable=True),
    sa.Column('comments_approved', sa.Integer(), nullable=True),
    sa.Column('is_commentable', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_splitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pbuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbarticlecomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('website', sa.Unicode(length=255), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.Column('rendered_body', sa.UnicodeText(), nullable=True),
    sa.Column('published', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.Column('xff_ip_address', sa.String(length=30), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['pbarticle.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pbarticlecomment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['pbuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['pbarticle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pbtag')
    op.drop_table('pbarticlecomment')
    op.drop_table('pbarticle')
    op.drop_table('pbverifiedemail')
    op.drop_table('pbuser')
    op.drop_table('pbstoragefile')
    op.drop_table('pbconfig')
    # ### end Alembic commands ###
